#!/bin/bash
# =============================================================================
# Set Copilot Environment Variables
# Configures FOUNDRY_ENDPOINT and FOUNDRY_AGENT_APP_ID for the target env
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"

ENVIRONMENT="${1:-staging}"

log() { echo "[$(date +%H:%M:%S)] $*"; }

# ---------------------------------------------------------------------------
# Resolve values
# ---------------------------------------------------------------------------
resolve_from_deploy_record() {
    local record="$PROJECT_ROOT/.deploy/last_publish.json"
    if [[ -f "$record" ]]; then
        FOUNDRY_AGENT_APP_ID=$(jq -r '.agent_id // empty' "$record")
        log "Resolved agent_id from deploy record: $FOUNDRY_AGENT_APP_ID"
    fi
}

resolve_endpoint() {
    if [[ -n "${FOUNDRY_ENDPOINT:-}" ]]; then
        log "FOUNDRY_ENDPOINT already set: $FOUNDRY_ENDPOINT"
        return 0
    fi

    # Try to resolve from Azure CLI
    if command -v az >/dev/null 2>&1; then
        local endpoint
        endpoint=$(az cognitiveservices account show \
            --resource-group "${FOUNDRY_RESOURCE_GROUP:-}" \
            --name "${FOUNDRY_WORKSPACE:-}" \
            --query "properties.endpoint" -o tsv 2>/dev/null || echo "")

        if [[ -n "$endpoint" ]]; then
            FOUNDRY_ENDPOINT="$endpoint"
            log "Resolved FOUNDRY_ENDPOINT from Azure: $FOUNDRY_ENDPOINT"
            return 0
        fi
    fi

    log "WARN: Could not auto-resolve FOUNDRY_ENDPOINT."
    log "Set it manually:"
    log "  export FOUNDRY_ENDPOINT=https://<your-foundry-resource>.cognitiveservices.azure.com"
}

# ---------------------------------------------------------------------------
# Write env files
# ---------------------------------------------------------------------------
write_env_snippet() {
    local env_file="$PROJECT_ROOT/.env.copilot.${ENVIRONMENT}"

    cat > "$env_file" <<ENV_EOF
# =============================================================================
# Copilot Environment — ${ENVIRONMENT^^}
# Generated by set_copilot_env.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)
# =============================================================================

# Foundry Agent Application
FOUNDRY_ENDPOINT=${FOUNDRY_ENDPOINT:-https://REPLACE_ME.cognitiveservices.azure.com}
FOUNDRY_AGENT_APP_ID=${FOUNDRY_AGENT_APP_ID:-REPLACE_ME}
FOUNDRY_TOKEN_SCOPE=https://cognitiveservices.azure.com/.default

# Azure Identity (Managed Identity preferred in production)
# AZURE_MANAGED_IDENTITY_CLIENT_ID=

# Copilot runtime
COPILOT_DEFAULT_MODE=PROD-ADVISORY
COPILOT_TIMEOUT_SECONDS=30
COPILOT_MAX_RETRIES=2

# Odoo bridge
COPILOT_ODOO_BASE_URL=${COPILOT_ODOO_BASE_URL:-http://localhost:8069}
COPILOT_LOG_LEVEL=INFO
COPILOT_AUDIT_ENABLED=true
ENV_EOF

    log "Env file written: $env_file"
}

write_infra_env_update() {
    local infra_env="$PROJECT_ROOT/infra/.env.example"

    if [[ -f "$infra_env" ]]; then
        # Check if copilot section already exists
        if ! grep -q "FOUNDRY_ENDPOINT" "$infra_env"; then
            cat >> "$infra_env" <<'INFRA_EOF'

# -----------------------------------------------------------------------------
# Copilot — Azure AI Foundry
# -----------------------------------------------------------------------------
FOUNDRY_ENDPOINT=
FOUNDRY_AGENT_APP_ID=
COPILOT_DEFAULT_MODE=PROD-ADVISORY
COPILOT_TIMEOUT_SECONDS=30
COPILOT_AUDIT_ENABLED=true
INFRA_EOF
            log "Added copilot section to infra/.env.example"
        else
            log "Copilot section already exists in infra/.env.example"
        fi
    fi
}

# ---------------------------------------------------------------------------
# Inject into docker-compose
# ---------------------------------------------------------------------------
print_compose_snippet() {
    log ""
    log "Add this to your Odoo service in docker-compose:"
    cat <<'COMPOSE_EOF'

    # In docker-compose.prod.yml, under the odoo service:
    environment:
      - FOUNDRY_ENDPOINT=${FOUNDRY_ENDPOINT}
      - FOUNDRY_AGENT_APP_ID=${FOUNDRY_AGENT_APP_ID}
      - FOUNDRY_TOKEN_SCOPE=${FOUNDRY_TOKEN_SCOPE:-https://cognitiveservices.azure.com/.default}
      - COPILOT_DEFAULT_MODE=${COPILOT_DEFAULT_MODE:-PROD-ADVISORY}
      - COPILOT_TIMEOUT_SECONDS=${COPILOT_TIMEOUT_SECONDS:-30}
      - COPILOT_AUDIT_ENABLED=${COPILOT_AUDIT_ENABLED:-true}
COMPOSE_EOF
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
main() {
    log "=== Copilot Environment Setup: $ENVIRONMENT ==="
    echo ""

    resolve_from_deploy_record
    resolve_endpoint
    write_env_snippet
    write_infra_env_update
    print_compose_snippet

    echo ""
    log "=== Done ==="
    log ""
    log "To activate:"
    log "  source .env.copilot.${ENVIRONMENT}"
    log ""
    log "For Docker Compose:"
    log "  cp .env.copilot.${ENVIRONMENT} .env"
    log "  docker compose -f infra/docker-compose.prod.yml up -d odoo"
}

main "$@"
